- lib/components/measurement_graph.dart
* remove overlapping dates
* show current range
* closes #13
> Improve graph usability

- lib/model/blood_pressure.dart
- lib/screens/settings.dart
* Show success message on import
* add error message on unknown error
> Import messages

- lib/components/display_interval_picker.dart
- lib/components/measurement_graph.dart
- lib/model/settings_store.dart
- test/model/settings_test.dart
The intervals in which the graph operates are now less confusing
> fix time steps

- lib/components/measurement_list.dart
- lib/model/settings_store.dart
- lib/screens/settings.dart
require confirmation when deleting an item and allow to undo deletion for 5 seconds
> safer deletion

- lib/model/blood_pressure.dart
To fix this commas in strings are now properly escaped by the csv lib instead of the custom implementation
> fix commas missing after import

- lib/components/display_interval_picker.dart
- lib/components/measurement_graph.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
Should make the display window more clear
> Add case specific interval display formats

- lib/components/display_interval_picker.dart
- lib/components/measurement_graph.dart
- lib/l10n/app_en.arb
- lib/model/settings_store.dart
Add time periods for last 7 days and last 30 days
> Feat relative time periods

- lib/components/measurement_list.dart
- lib/components/settings_widgets.dart
- lib/main.dart
- lib/screens/add_measurement.dart
- lib/screens/statistics.dart
- lib/screens/subsettings/enter_timeformat.dart
- pubspec.lock
- pubspec.yaml
- use the latest compatible version of all direct dependencies
- futter and dart upgrade
- migrate to Material 3 (You)
> Upgrade dependencies and sdk

- lib/main.dart
- lib/model/export_options.dart
- lib/screens/subsettings/export_import_screen.dart
- reworks the conditions
- localize missing formats
- fix warn banner confirm
> Fix export page warn banner

- lib/l10n/app_en.arb
- lib/screens/error_reporting.dart
- lib/screens/subsettings/version.dart
Shared preferences were removed and are no longer needed for debugging purposes.
> remove in-app references to shared preferences

- lib/main.dart
- lib/model/export_options.dart
- lib/screens/subsettings/export_import_screen.dart
(internal changes to code structure)
> remove global app localizations object

- test/ui/components/measurement_list_entry_test.dart
- test/ui/navigation_test.dart
- test/ui/statistics_test.dart
> Add tests for null values

- lib/components/dialoges/add_export_column_dialoge.dart
- lib/components/dialoges/add_measurement_dialoge.dart
- lib/components/dialoges/enter_timeformat_dialoge.dart
- lib/components/dialoges/fullscreen_dialoge.dart
- lib/components/dialoges/input_dialoge.dart
- lib/l10n/app_en.arb
- lib/main.dart
- lib/model/blood_pressure_analyzer.dart
- lib/model/storage/settings_store.dart
- lib/screens/settings_screen.dart
- test/model/json_serialization_test.dart
- test/ui/components/enter_timeformat_dialoge_test.dart
Adds option to move app bars to the bottom of the screen for easier access.
Also fixes a critical bug where the analyzer would break with only 2 incomplete records.
> 244 feature bottom app bar

- lib/components/export_warn_banner.dart
- lib/main.dart
- lib/model/export_import/column.dart
- lib/model/export_import/export_configuration.dart
- lib/model/export_import/pdf_converter.dart
- lib/model/storage/export_pdf_settings_store.dart
Although I am highly confident exporting more entries will never lead to data loss, more investigation of edge cases (one long line is needed. This should be safe nevertheless as no data will be lost and effects won't propagate through the entire pdf.
> 2 column pdfs

- lib/model/blood_pressure/model.dart
- lib/model/blood_pressure/needle_pin.dart
- lib/model/export_import/column.dart
- lib/model/export_import/record_formatter.dart
The db model had a error when attempting to encode a color
> Fix saving measurements with colors

- app/lib/model/blood_pressure/medicine/intake_history.dart
> Stop crashing when converting invalid medicine intakes

- app/lib/model/export_import/pdf_converter.dart
- app/test/model/export_import/column_test.dart
- app/test/model/export_import/record_formatter_test.dart
- health_data_store/lib/src/types/units/pressure.dart
- health_data_store/test/src/types/units/pressure_test.dart
Fixes #356 and tests for problems like these in all parts of the app that have unit test coverage.
> Fix PDF statistics generation

- app/lib/features/measurement_list/compact_measurement_list.dart
- app/lib/features/measurement_list/legacy_measurement_list.dart
- app/lib/screens/home_screen.dart
- app/test/features/measurement_list/compact_measurement_list_test.dart
Help dart finding the correct method by explicitly providing a type. Additionally remove remainders of legacy status of compact measurement list.
> Fix compact list edit and delete

- app/lib/data_util/interval_picker.dart
- app/test/data_util/interval_picker_test.dart
caused by typo, found in v1.8.0 qs
> Fix interval picker jumping back by 11 years

- app/lib/data_util/entry_context.dart
> Set to most recent interval before exporting

- app/lib/features/statistics/blood_pressure_distribution.dart
> Change color on distribution selection change

- app/lib/features/input/add_bodyweight_dialoge.dart
- app/lib/features/input/add_measurement_dialoge.dart
- app/lib/features/measurement_list/weight_list.dart
- app/lib/l10n/app_en.arb
- app/test/features/input/add_bodyweight_dialoge_test.dart
- app/test/features/input/add_measurement_dialoge_test.dart
implements #309
https://github.com/user-attachments/assets/a9db88e3-98f0-4c1f-8433-f9b79b8b8a81
> Implement simple weight input

- health_data_store/lib/src/repositories/bodyweight_repository_impl.dart
- caused test failure
- was more complex than necessary
- was wrong
> Fix wrong sql querry in data package

- .github/workflows/app-CI.yml
- .github/workflows/pr.yml
Followup on #442, fixes some bugs in the new workflows
> Fix PR builds

- app/lib/features/input/add_bodyweight_dialoge.dart
- app/lib/features/measurement_list/weight_list.dart
- app/lib/l10n/app_en.arb
- app/lib/model/blood_pressure/pressure_unit.dart
- app/lib/model/storage/settings_store.dart
- app/lib/model/weight_unit.dart
- app/lib/screens/settings_screen.dart
- app/pubspec.lock
- app/test/features/input/add_bodyweight_dialoge_test.dart
- app/test/features/input/add_measurement_dialoge_test.dart
- app/test/features/measurement_list/weight_list_test.dart
- app/test/model/json_serialization_test.dart
- app/test/model/weight_unit_test.dart
> Implement preferred weight unit

- app/lib/screens/home_screen.dart
- app/test/screens/home_screen_test.dart
- app/test/util.dart
The horizontal graph was not wrapped in a scaffold leading to missing background theming, and text style. fixes #463
> Fix horizontal graph theme

- app/lib/features/statistics/value_graph.dart
- app/test/screens/home_screen_test.dart
> Fix start of warn area not filled at specific angles

- app/lib/features/statistics/value_graph.dart
fixes #484
The lack of semantics makes this really hard to test. At some point they should be added as well
> Fix hour:minute precision in homescreen graph

- .github/workflows/pkg-CI.yml
https://github.com/tekartik/sqflite/blob/c04dc55c193047944c430896acf6eb1ee27a63cd/sqflite_common_ffi/doc/troubleshooting.md
> Ensure newest sqlite available in packages ci

- app/lib/data_util/entry_context.dart
- app/lib/features/export_import/export_button.dart
- app/lib/features/input/add_entry_dialogue.dart
- app/lib/features/input/forms/add_entry_form.dart
- app/lib/features/settings/version_screen.dart
- app/lib/logging.dart
- app/lib/model/export_import/csv_converter.dart
- app/test/features/input/forms/add_entry_form_test.dart
Recent issues #552, #556, and #558 aren't reproducible and thus hard to debug. This PR adds more extensive debug logging options that to help to reproduce and fix these issues.
> Allow creating detailed logs in production apps

- fastlane/metadata/android/cs-CZ/changelogs/49.txt
- fastlane/metadata/android/de-DE/changelogs/49.txt
- fastlane/metadata/android/en-US/changelogs/49.txt
- fastlane/metadata/android/es-ES/changelogs/49.txt
- fastlane/metadata/android/et/changelogs/49.txt
- fastlane/metadata/android/fr-FR/changelogs/49.txt
- fastlane/metadata/android/hu-HU/changelogs/49.txt
- fastlane/metadata/android/it-IT/changelogs/49.txt
- fastlane/metadata/android/nl-NL/changelogs/49.txt
- fastlane/metadata/android/no-NO/changelogs/49.txt
- fastlane/metadata/android/pt-BR/changelogs/49.txt
- fastlane/metadata/android/pt/changelogs/49.txt
- fastlane/metadata/android/ru-RU/changelogs/49.txt
- fastlane/metadata/android/sl/changelogs/49.txt
- fastlane/metadata/android/sv-SE/changelogs/49.txt
- fastlane/metadata/android/ta-IN/changelogs/49.txt
- fastlane/metadata/android/tr-TR/changelogs/49.txt
- fastlane/metadata/android/zh-CN/changelogs/49.txt
- fastlane/metadata/android/zh-TW/changelogs/49.txt
avoid unused translation effort
> Remove published changelogs

- BLUETOOTH.md
I am not sure about downloading data, but immediate input is possible one entry at a time.
> Added Omron X2 Smart+ to BLUETOOTH.md

- app/lib/features/input/forms/add_entry_form.dart
- app/lib/features/input/forms/date_time_form.dart
- app/test/features/input/forms/add_entry_form_test.dart
- app/test/features/input/forms/date_time_form_test.dart
> Fix input form being unsubmitable without time sub-form
