derdilla/blood-pressure-monitor-fl

- lib/components/display_interval_picker.dart
- lib/model/ram_only_implementations.dart
- lib/model/settings_store.dart
- lib/screens/add_measurement.dart
To avoid missing new entries the display time frame is now forcefully reset to the newest date after adding a measurement.
> Fix newest entries missing

- lib/components/measurement_graph.dart
- lib/l10n/app_en.arb
- lib/model/ram_only_implementations.dart
- lib/model/settings_store.dart
- lib/screens/settings.dart
- test/model/settings_test.dart
Fixes graph labels showing not often enough or too often, by determining the amount of times it shows up automatically.
The graph labels are now more useful as well, as they depend on the values that are actually shown. For example, the year interval is selected but only a week of data is collected, the labels give more precise information than just the month.
> fix graph labels

- lib/components/consistent_future_builder.dart
- lib/components/export_item_order.dart
- lib/components/legacy_measurement_list.dart
- lib/screens/statistics.dart
- lib/screens/subsettings/export_import_screen.dart
Some elements, like the version indicator in the settings used to flash when rebuilt. The workaround / correct implementation is now part of the general ConsistentFutureBuilder implementation.
> Avoid ConsistentFutureBuilder rebuilding

- lib/model/blood_pressure.dart
- lib/model/export_import.dart
- lib/screens/home.dart
- lib/screens/statistics.dart
- pubspec.lock
- pubspec.yaml
- test/model/bood_pressure_test.dart
Desktop support wasn't continued early in development. This PR removes the dead legacy code and removes the desktop sqflite extension.
This causes a reduction of app size by 0.2MB.
It also fixes a minor bug where the export of PDF files with a title would not work when no data is present.
> Drop desktop support

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/drawable-v21/ic_launcher_monochrome.xml
- android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
> [Feature] Themed / Monochrome icon support

- app/lib/components/statistics/value_distribution.dart
- app/test/ui/components/statistics/value_distribution_test.dart
- fixed offset by one bug in case there is no measurements with valuemax-1
- fixed bar order in graph, map keys not sorted
> fixed value distribution graph

- health_data_store/lib/src/database_helper.dart
- health_data_store/lib/src/database_manager.dart
- health_data_store/lib/src/repositories/blood_pressure_repository_impl.dart
- health_data_store/lib/src/repositories/medicine_intake_repository_impl.dart
- health_data_store/lib/src/repositories/note_repository_impl.dart
- health_data_store/lib/src/repositories/repository.dart
- health_data_store/test/src/database_helper_test.dart
- health_data_store/test/src/repositories/blood_pressure_repository_test.dart
- health_data_store/test/src/repositories/medicine_intake_repository_test.dart
- health_data_store/test/src/repositories/note_repository_test.dart
On data import duplicate entries could be created. This is fixed by dropping support for entries at the same time. The new default behavior is overriding the old value similar to the old storage
> Fix duplicate entries on import

- app/lib/app.dart
- app/lib/components/fullscreen_dialoge.dart
- app/lib/main.dart
- app/test/components/fullscreen_dialoge_test.dart
fixes #232
- add 4 units of padding to the top of dialoges when using bottom app bars
- fixes hot reload for faster dev
- removes unused close callback functionality from fullscreen dialoge
- adds tests for existing and new features of fullscreen dialoge
> Add padding to top when using bottom app bar

- app/lib/features/export_import/export_button_bar.dart
- health_data_store/lib/src/database_manager.dart
- health_data_store/lib/src/health_data_store.dart
- health_data_store/test/src/database_manager_test.dart
- health_data_store/test/src/health_data_store_test.dart
fixes #360
Unfortunately sqflite doesn't provide information on whether an database is read-only. Therefore a parameter needs to be manually passed.
> fix write attempts on db import

- app/lib/features/export_import/export_button_bar.dart
- app/lib/features/export_import/import_preview_dialoge.dart
- app/lib/l10n/app_en.arb
- app/lib/model/export_import/column.dart
- app/lib/model/export_import/csv_converter.dart
- app/lib/model/export_import/export_configuration.dart
- app/lib/model/export_import/import_field_type.dart
- app/lib/model/export_import/record_formatter.dart
- app/test/features/bluetooth/mock/fake_device.dart
- app/test/features/export_import/import_preview_dialoge_test.dart
- app/test/model/export_import/column_test.dart
- app/test/model/export_import/csv_converter_test.dart
closes #326
Medicine intakes can now be exported to CSV of the format `MedName1(123.0)|MedName2(456.0)` with the number representing dosis in mg. Import of that data is possible as long as there is a medicine with matching designation.
The alternative approach with columns for each medicine wasn't compatible with the column selection logic.
> Allow medicine intake export and import

- app/lib/app.dart
- app/lib/l10n/app_en.arb
- app/lib/model/storage/settings_store.dart
- app/lib/screens/settings_screen.dart
- app/pubspec.lock
- app/pubspec.yaml
closes #325
Due to flutters architecture enabling desktop support is rather simple. There is no impact on the normal app size due to optimizations done by the compiler. 
This should make development faster.
> Reintroduce desktop support

- app/lib/features/input/add_measurement_dialoge.dart
- app/lib/features/input/forms/date_time_form.dart
The font for medication selection used to be too wide and colors of different input fields used to slightly mismatch. Not using bodyLarge style for all inputs. 
```dart
Theme.of(context).textTheme.bodyLarge
```
<details><summary>Sample render</summary>
</details>
> Unify input dialoge text style

- .github/workflows/app-CI.yml
Unfortunately flutter seems to render slightly different on GitHub CI than locally. To still allow running golden tests in CI a PR gets created for golden changes. This also allows for easy inspections of golden failures.
Sample PR: #391
> Update goldens in CI

- app/lib/model/storage/db/file_settings_loader.dart
Tiny fix, while starting the app on Linux the app had a fatal error because by default it creates new databases in the `app/.dart_tool/sqflite_common_ffi/databases/` folder while only `app/.dart_tool` already exists by default
> fix: create database path recursively

- app/lib/features/statistics/value_graph.dart
- app/test/features/statistics/value_graph_test.dart
closes #460
Previously if either category (sys,dia,pul) had less than 3 values the graph wouldn't draw. This didn't make a lot of sense for folks not entering pulse (as [GiovanniManieri](https://github.com/GiovanniManieri) thankfully pointed out), so now the graph is rendered when at least one category has 2 or more values.
> Fix graph relies on pulse

- app/lib/data_util/interval_picker.dart
- app/test/data_util/interval_picker_test.dart
When picking custom time the picker didn't ensure the end of the day (23:59:59) is selected, which resulted in newer measurements not being shown (on list and export). 
This PR:
- ensures the time is set to the end of the day
- adds proper testing to interval pickers custom range selection
closes #466
> Fix custom date range ending before midnight

- app/android/app/build.gradle
- app/android/gradle/wrapper/gradle-wrapper.properties
- app/android/settings.gradle
- app/macos/Flutter/GeneratedPluginRegistrant.swift
- app/pubspec.lock
With a new release around the corner this is a bit of a cherry-pick from #432 (thanks for the suggestion @pimlie). Flutter prefers these new versions, so why not use them for a stable release.
Also applies suggestions from [this issue](https://github.com/fluttercommunity/plus_plugins/issues/3303)
You may still get something around the lines "Your project is configured with Android NDK 23.1.7779620, but the following plugin(s) depend on a different Android NDK version:" listing a bunch of android plugins. This is probably a android studio configuration error? You _could_ change ndkVersion locally to the one suggested, or install the proper NDK in android studio ladybug, but this isn't a problem for compilation so its fine as is (as stated in the above mentioned issue)
> Update android files

- app/analysis_options.yaml
This PR removes the lint as it has occasional false-positives (as mentioned in [the docs](https://dart.dev/tools/linter-rules/avoid_redundant_argument_values)) and there is no strong reasoning to keep it. 
While it can be used to automatically switch to better defaults, I could even argue that it is equally as likely to be harmful when the default changes. It discourages explicitly enumerating a default value in cases where only the default value makes sense. This way context is effectively lost.
> Remove avoid_redundant_argument_values lint

- app/lib/model/export_import/pdf_converter.dart
When dividing the table for multi-column layout there was a bug in the algorithm: After computing the amount of rows available it increments the current row index by that count and takes the data from *after* the last end index up to, *excluding*, the new end index. While the first one was intentional to avoid negative indexing on the first page, excluding the new end index is entirely unnecessary and was likely introduced during a refactor.
fixes #485
> Fix multicolumn PDF export missing rows at table breaks

- app/lib/features/input/add_measurement_dialoge.dart
- app/lib/features/old_bluetooth/bluetooth_input.dart
- app/lib/features/old_bluetooth/logic/ble_read_cubit.dart
- app/lib/features/old_bluetooth/logic/ble_read_state.dart
- app/lib/features/old_bluetooth/logic/bluetooth_cubit.dart
- app/lib/features/old_bluetooth/logic/bluetooth_state.dart
- app/lib/features/old_bluetooth/logic/characteristics/ble_date_time.dart
- app/lib/features/old_bluetooth/logic/characteristics/ble_measurement_data.dart
- app/lib/features/old_bluetooth/logic/characteristics/ble_measurement_status.dart
- app/lib/features/old_bluetooth/logic/characteristics/decoding_util.dart
- app/lib/features/old_bluetooth/logic/device_scan_cubit.dart
- app/lib/features/old_bluetooth/logic/device_scan_state.dart
- app/lib/features/old_bluetooth/logic/flutter_blue_plus_mockable.dart
- app/lib/features/old_bluetooth/ui/closed_bluetooth_input.dart
- app/lib/features/old_bluetooth/ui/device_selection.dart
- app/lib/features/old_bluetooth/ui/input_card.dart
- app/lib/features/old_bluetooth/ui/measurement_failure.dart
- app/lib/features/old_bluetooth/ui/measurement_success.dart
- app/lib/l10n/app_en.arb
- app/lib/model/storage/bluetooth_input_mode.dart
- app/lib/model/storage/settings_store.dart
- app/lib/screens/settings_screen.dart
- app/test/features/bluetooth/mock/fake_characteristic.dart
- app/test/features/bluetooth/mock/fake_service.dart
- app/test/features/input/add_measurement_dialoge_test.dart
- app/test/model/json_serialization_test.dart
Releases since 1.8.1 happened from a special branch without the new Bluetooth back-end with the expectation that this will be completed and tested soon. Since this is evidently not the case this PR reintroduces the old back-end and makes the new one toggle-able through a settings switch.
> Make new BLE implementation choosable

- app/pubspec.yaml
For f-droid to change their scripts a build needs to fail.
> Remove f-droid-flutter from pubspec
